### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by nadiapolonia** [nadiapolonia/assignments#30]
# Key areas of Information to include:

## Contact information
- [ ] Email
- [ ] Phone Number (Google numbers are great if you want to protect your personal number)
- [ ] Github link
- [ ] Portfolio link

## Summary
- [ ] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [ ] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [ ] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [ ] Write where you went college and your degree.
- [ ] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [ ] Upload or submit a link to your resume for review.

**Comment by nadiapolonia** [comment]
[Nadia's Resume (1).pdf](https://github.com/nadiapolonia/assignments/files/3659304/Nadia.s.Resume.1.pdf)

**Comment by ktrammell95** [comment]
This is a great start! You have a good layout and your past experience is written out very well. I would see if you can beef up your projects by adding a link to the GitHub repositories. Also, make sure to make all links clickable when someone is accessing it on a computer.

Overall very nice!
